name: publish

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Make sure tests pass
        run: uv run --extra dev --python 3.12 pytest

      - name: Strip unsupported tags in README
        run: |
          sed -i '/<!-- pypi-strip -->/,/<!-- \/pypi-strip -->/d' README.md

      - name: Setup Node.js for template build
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build web template
        working-directory: src/muwanx/template
        run: |
          npm install
          npm run build

      - name: Remove artifacts from pypi package
        working-directory: src/muwanx/template
        run: |
          rm -rf node_modules
          rm -rf .nodeenv

      - name: Build and publish
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uv publish
